# Generated by Django 3.0.7 on 2020-06-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, verbose_name='emailAddress')),
                ('key', models.CharField(max_length=100, verbose_name='key')),
            ],
            options={
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mobile', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='mobile')),
                ('nickname', models.CharField(default=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='mobile'), max_length=20, verbose_name='nickname')),
                ('sex', models.CharField(max_length=20, verbose_name='password')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.User'),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('user', 'email')},
        ),
    ]
