# Generated by Django 3.0.7 on 2020-06-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20200612_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='id',
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='emailAddress'),
        ),
    ]
