# Generated by Django 3.0.7 on 2020-06-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20200613_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='imap_host',
        ),
        migrations.RemoveField(
            model_name='email',
            name='imap_port',
        ),
        migrations.RemoveField(
            model_name='email',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='email',
            name='smtp_port',
        ),
    ]
