# Generated by Django 3.0.7 on 2020-06-18 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20200618_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='imap_port',
        ),
        migrations.RemoveField(
            model_name='email',
            name='smtp_port',
        ),
    ]
