# Generated by Django 3.0.7 on 2020-06-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_auto_20200618_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='imap_host',
            field=models.CharField(max_length=50, verbose_name='imap_host'),
        ),
        migrations.AlterField(
            model_name='email',
            name='smtp_host',
            field=models.CharField(max_length=50, verbose_name='smtp_host'),
        ),
    ]
